version: '3'
volumes:
  web_data:
    external: true
services:
  web-front:
    #Dockerfile del Front o su imagen
    build: DockerfileFront
    ports:
      - "80:80"
  web-back:
    #Doc
    #image: proyecto-final-django_web:latest
    build: DockerfileBack
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
  bd: 
    image: clue/json-server:latest
    volumes:
      - ./database/db.json:/data/db.json 
    ports:
      - "3000:80"
